#!/bin/sh

usage() {
    cat<<USAGE

Usage: ${0##*/} [OPTION] <file>
options:
  -help          | print the usage
  -device        | -d <name> set the graph title (default "jpeg")
  -figName       | -n <name> set the graph title (default "Data Monitoring")
  -figTitle      | -t <title> set the graph title (default "Data Monitoring")
  -figSize       | -s <size>  set the size of the output plot, format "640,480"
  -YAxislogscale | -l         plots data (y-axis) on log scale, e.g. for residuals
  -refresh       | -r <time>  refreshes display every <time> sec (default 1s)
  -idle          | -i <time>  stops if <file> unchanging for <time> sec (default 60s)

Monitor data with Gnuplot from time-value(s) graphs written by OpenFOAM.
Edit by keepone, this script generate jpg file every <time> seconds
- requires gnuplot

Example:
  actMonitor -l /path/to/your/residuals.dat

USAGE
}
#  -YAxisRange    | -y <range> sets data (y-axis) range, format "[0:1]"

error() {
    exec 1>&2
    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
    usage
    exit 1
}

plotFileHeader() {
cat<<EOF
set encoding utf8
set terminal $gpterminal $font $lw $size 
set output "$output" 
$logscale
set yrange [1e-10<*:*]
set xrange [0:]
set ytics format "$yticFormat"
set title "$title"
set xlabel "$xlabel"
set key outside bottom samplen 2 spacing .8 font "FreeSerif, 10"
plot \\
EOF
}

plotFileFooter() {
    cat<<EOF

pause $refresh
reread
EOF
}

howMany() ( echo "$1" | awk '{ print NF }' )
#howMany() ( echo "$1" | set -f; set -- $1; echo $# )

isInteger() {
    [ ! -z "${1##*[!0-9]*}" ] && echo "$1" && return 0
}

idle=60
refresh=1
logscale=""
yrange=""
yticFormat="%g"
title="Data Monitoring"
size="size 640,480"
output="residual.jpg"
font='font "FreeSerif, 15"'
lw='linewidth 2'
gpterminal='jpeg'

command -v gnuplot >/dev/null 2>&1 || error "Gnuplot not installed"

# parse options
while [ "$#" -gt 0 ]
do
    case "$1" in
    -h | -help)
        usage && exit 0
        ;;
    -i | -idle)
        [ "$#" -ge 2 ] || error "'$1' option requires an argument"
        idle=$(isInteger "$2") || error "Argument of '$1' is not an integer: '$2'"
        shift 2
        ;;
    -l | -logscale)
        logscale="set logscale y"
        yticFormat="%1.e"
        shift 1
        ;;
    -t | -title)
        [ "$#" -ge 2 ] || usage "'$1' option requires an argument"
        title=$2
        shift 2
        ;;
    -r | -refresh)
        [ "$#" -ge 2 ] || error "'$1' option requires an argument"
        refresh=$(isInteger "$2") || error "Argument of '$1' is not an integer: '$2'"
        shift 2
        ;;
    -y | -yrange)
        [ "$#" -ge 2 ] || error "'$1' option requires an argument"
        yrange="set yrange $2"
        shift 2
        ;;
    -s | -size)
        [ "$#" -ge 2 ] || error "'$1' option requires an argument"
        size="size $2"
        shift 2
        ;;
    -n | -figName)
        [ "$#" -ge 2 ] || error "'$1' option requires an argument"
        output="$2"
        shift 2
        ;;
    -d | -device)
        [ "$#" -ge 2 ] || error "'$1' option requires an argument"
        gpterminal="$2"
        shift 2
        ;;
    -*)
        error "unknown option: '$*'"
        ;;
    *)
        break
        ;;
    esac
done

[ $# -eq 1 ] || error "Incorrect arguments specified"
[ -f "$1" ]  || error "File $1 does not exit"
file=$1

# wait until file contain 1 lines data
while true
do 
    flag=$(grep -c -E '^[0-9]' $file)
    # echo $flag
    if [ -z "$flag" ]; then
        # echo "empty, waiting";
        continue;
    elif [ $flag -lt 3 ]; then
        # echo "lt 3 , waiting";
        sleep 1;
    else
        break;
    fi;
done 

# Get keys from header
keys=$(sed -n '2p;3q' "$file")
# echo $keys

[ "x$keys" = "x" ] && keys="# Step"
n_keys=$(howMany "$keys")
n_cols=$(sed -n '3p;4q' "$file" | awk '{ print NF }')


# With full column labels, n_keys = n_cols + 1, since it includes "#"

# If n_keys > n_cols + 1, REMOVE EXCESS keys
n_cols_pone=$(( n_cols + 1 ))
[ "$n_keys" -gt "$n_cols_pone" ] && \
    keys=$(echo "$keys" | cut -d" " -f1-$n_cols_pone)
n_keys=$(howMany "$keys")

i=0
while [ "$n_keys" -le "$n_cols" ]
do
    i=$(( i + 1 ))
    keys="$keys data$i"
    n_keys=$(howMany "$keys")
done

# Remove # and Time keys
xlabel=$(echo "$keys" | cut -d " " -f2)
keys=$(echo "$keys" | cut -d " " -f3-)

gp_file=$(mktemp /tmp/tmp.XXXXXX)
plotFileHeader > "$gp_file"
i=1
for field in $keys
do
    i=$(( i + 1 ))
    plot_line="\"$file\" using 1:${i} with lines title \"$field\""
    if [ $i -lt "$n_cols" ]
    then
       plot_line="$plot_line, \\"
    fi
    echo "$plot_line" >> "$gp_file"
done
plotFileFooter >> "$gp_file"

touch "$file"
gnuplot "$gp_file" &
pid=$!

while true
do
    mod_time=$(stat --format=%Y "$file")
    idle_ago=$(( $(date +%s) - idle ))
    test "$mod_time" -gt "$idle_ago" || break
    sleep "$refresh"
done

kill -9 $pid
# echo $gp_file
rm "$gp_file"

#------------------------------------------------------------------------------
